### ISSUE TITLE
Transforms change on window focus/blur when using fixed positioning

### ISSUE THREAD

**Issue by CatchABus** [jscottsmith/parallax-controller#15]
I started using this package for implementing parallax effects in our website and it looks simple yet powerful.
Unfortunately, I came across transformation issues when I navigated between browser tabs or made window get/lose focus in any way.

In my case, every time window loses focus my translate transformation changes position if I have scrolled prior to it. I have created a code pen sample to demonstrate: https://codepen.io/catchabus/pen/WNabdwp

The following screenshots show how I reproduce the problem using devtools to make window get/lose focus.

### Here is how my sample looks after a mere scrolling:

![Screenshot from 2023-04-08 16-36-11](https://user-images.githubusercontent.com/55595100/230724155-055283db-cf26-4325-ac8f-b41f6fda52f5.png)

### Now, click inside rendered content and then click on devtools. The result will be this:
![Screenshot from 2023-04-08 16-36-26](https://user-images.githubusercontent.com/55595100/230724196-f684e021-8817-4bb8-9209-15e3fa72844c.png)

Please notice the scroll bar, it's still in the same height.
If you scroll to another position below or above center and repeat the steps, the problem will occur over and over.

Note: This isn't a devtools-specific problem. In the sample you can click on content without devtools and reproduce it since iframe is not focused when page loads. Also on a live website, it can occur on browser tab change.

I did my research on sources and found it library uses listeners to update its cache.
https://github.com/jscottsmith/parallax-controller/blob/master/src/classes/ParallaxController.ts#L127
I managed to get rid of the problem in my website by commenting out a couple of scroll x/y additions.
https://github.com/jscottsmith/parallax-controller/blob/master/src/helpers/createLimitsWithTranslationsForRelativeElements.ts#L82
https://github.com/jscottsmith/parallax-controller/blob/master/src/helpers/createLimitsWithTranslationsForRelativeElements.ts#L138

Everywhere that `scroll.y` or `scroll.x` is added, there is a malformed result.

**Comment by jscottsmith** [comment]
Ya a lot of values are cached when the controller is created and are then updated based upon certain events that may or may not have caused the layout to change (such as a window resize). In this case a focus event updates the controller to the most current values, and I assume, the correct ones.

In the CodePen it looks like the values that are used when the controller is created change after. This could be because of the iframe and various Codepen UI. When I view the pen in the debug mode (without all Codepen UI) it seems to have the expected behavior which is it uses correct values on load and does not shift on a focus event.

It sounds like the main issue you are having is the values that are being cached are incorrect and a focus event is updating them which seems jarring. If that's the case we need to figure out why the values are wrong. This could be caused by a whole number of things since layout changes often as the page loads.

If you send a test link I'm happy to take a look at your specific use case.

**Comment by CatchABus** [comment]
> Ya a lot of values are cached when the controller is created and are then updated based upon certain events that may or may not have caused the layout to change (such as a window resize). In this case a focus event updates the controller to the most current values, and I assume, the correct ones.
> 
> In the CodePen it looks like the values that are used when the controller is created change after. This could be because of the iframe and various Codepen UI. When I view the pen in the debug mode (without all Codepen UI) it seems to have the expected behavior which is it uses correct values on load and does not shift on a focus event.
> 
> It sounds like the main issue you are having is the values that are being cached are incorrect and a focus event is updating them which seems jarring. If that's the case we need to figure out why the values are wrong. This could be caused by a whole number of things since layout changes often as the page loads.
> 
> If you send a test link I'm happy to take a look at your specific use case.

Thanks for the quick response. My website is not live but I managed to update my sample to make issue reproducible even in debug mode: https://codepen.io/catchabus/pen/WNabdwp
In the new sample, it's still about red layer's miscalculated translate point.

You can reproduce it with browser tab change too.

### Before blur
![Screenshot from 2023-04-11 21-09-29](https://user-images.githubusercontent.com/55595100/231252267-e4ee6788-4356-4b02-b4ae-9236735067a9.png)

### After blur
![Screenshot from 2023-04-11 21-10-15](https://user-images.githubusercontent.com/55595100/231252336-3772a78f-4cb2-429b-a74b-6799bcc5870e.png)

**Comment by jscottsmith** [comment]
Ahh, I see your issue now: you are using `fixed` positioning. 

The way this lib works is by tracking an [element's progress through the view as you scroll](https://react-scroll-parallax.damnthat.tv/docs/examples/how-it-works#progress-is-relative-to-the-view), but when you use fixed positioning the element is removed from the scrolling context so this causes issues.

The best way around this is to use a [`targetElement`](https://parallax-controller.damnthat.tv/docs/usage/advanced#using-a-target-element) to determine the progress of the animation.

I mocked up an example similar to yours using a target element: https://codepen.io/jscottsmith/pen/rNqeWMd

Hope that clarifies things.

**Comment by CatchABus** [comment]
> Ahh, I see your issue now: you are using `fixed` positioning.
> 
> The way this lib works is by tracking an [element's progress through the view as you scroll](https://react-scroll-parallax.damnthat.tv/docs/examples/how-it-works#progress-is-relative-to-the-view), but when you use fixed positioning the element is removed from the scrolling context so this causes issues.
> 
> The best way around this is to use a [`targetElement`](https://parallax-controller.damnthat.tv/docs/usage/advanced#using-a-target-element) to determine the progress of the animation.
> 
> I mocked up an example similar to yours using a target element: https://codepen.io/jscottsmith/pen/rNqeWMd
> 
> Hope that clarifies things.

Oh I see, thanks for the details!
Maybe lib could display a warning for fixed elements that don't use `targetElement`. This would discourage other people from following the same principle.

**Comment by jscottsmith** [comment]
Yes absolutely, I will create an issue to update the docs. Thanks for the feedback.
