### ISSUE TITLE
Specify translateY in vh unit instead of px or %

### ISSUE THREAD

**Issue by AFusco** [jscottsmith/parallax-controller#6]
Apparently vh and vw units are not currently supported.

If it's just matter of adding it to the typescript definitions, I will be glad to create a pull request.

But, by looking at [parseValueAndUnit.test.ts](https://github.com/jscottsmith/parallax-controller/blob/f8b0c8d1530f73666ed9142e1200b9ee55f6afa3/src/utils/parseValueAndUnit.test.ts#L39-L41), it looks like vh is not supported on purpose.

Do you have any advice on how to approach this problem?

**Comment by jscottsmith** [comment]
It's not currently supported and a bit more involved than just adding the ts definitions.

That said, it should be possible -- I'll look into it.

**Comment by jscottsmith** [comment]
published in [1.4.0](https://github.com/jscottsmith/parallax-controller/releases/tag/v1.4.0)
